print("Ejemplo de listas")
arcoiris=["verde","azul","morado"]
print(arcoiris)
longitud=len(arcoiris)
print(longitud)
print("Elementos que contiee la lista arcoiris ", longitud)
print("Elementos que contiee la lista arcoiris v2 {longitud}")
print("Accediendo a un elemento de la lista ")
print(arcoiris[1])
print(f"Elemento en la posicion 0 es {arcoiris[0]}")
print("Agregar un elemento de la lista")
print(arcoiris)
arcoiris.append("naranja")
print(arcoiris)